"""add language to posts

Revision ID: 28627a9a97ea
Revises: 4c67a0bc6d1a
Create Date: 2023-05-25 15:18:06.283016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28627a9a97ea'
down_revision = '4c67a0bc6d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
